# Generated by Django 3.2.9 on 2022-01-13 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trayecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=30)),
                ('destiny', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('estimated_duration', models.TimeField()),
                ('periodicity', models.IntegerField()),
                ('places_offered', models.IntegerField()),
                ('price', models.FloatField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.usuario')),
                ('passengers', models.ManyToManyField(blank=True, related_name='_crud_trayecto_passengers_+', to='crud.Usuario')),
            ],
        ),
    ]
