# Generated by Django 3.2.9 on 2022-01-18 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userOne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='crud.usuario')),
                ('userTwo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.conversacion')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.usuario')),
            ],
        ),
    ]
