# Generated by Django 3.2.9 on 2022-01-13 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_auto_20220113_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reputacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reputationStars', models.IntegerField(choices=[('1', '*'), ('2', '**'), ('3', '***'), ('4', '****'), ('5', '*****')], max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.usuario')),
            ],
        ),
    ]
