# Generated by Django 3.2.9 on 2022-01-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_reputacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reputacion',
            name='reputationStars',
            field=models.IntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')], max_length=1),
        ),
    ]
