# Generated by Django 3.2.9 on 2022-01-13 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_alter_reputacion_reputationstars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reputacion',
            old_name='reputationStars',
            new_name='Stars',
        ),
    ]
