# Generated by Django 3.2.9 on 2022-02-09 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_conversacion_mensaje'),
        ('crud', '0003_usuario_email'),
        ('crud', '0007_rename_reputationstars_reputacion_stars'),
    ]

    operations = [
    ]
