# Generated by Django 3.2.9 on 2022-02-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_merge_20220209_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
